spring.application.name=UserService
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/p19_complaintmonitoring_and_resolutionsystem_populated_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
